server:
  port: 19092

spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:./config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/