server:
  port: 19091  # ????? ???? ??? ?? ??

spring:
  main:
    web-application-type: reactive  # Spring ??????? ???? ? ???????? ???
  application:
    name: gateway-service  # ?????? ??? 'gateway-service'? ??
  cloud:
    gateway:
      server:
        webflux:
          routes:  # Spring Cloud Gateway? ??? ??
            - id: demo-service
              uri: lb://demo-service  # 'order-service'?? ???? ?? ???? ???? ???
              predicates:
                - Path=/demo/**
          discovery:
            locator:
              enabled: true  # ??? ?????? ?? ???? ???? ????? ??

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka ??? URL? ??